### PR TITLE
created news.html file

### PR DESCRIPTION
**Pull request by ywalia01**

### CODE REVIEW

**Comment by rahul799** [comment]
Good job @ywalia01 . Now can you please attach a screen shot so it will be easy for me to review.

**Comment by ywalia01** [comment]
Im sorry but i dont understand what you mean by screenshot

**Comment by ywalia01** [comment]
Screenshot 2020-06-05 at 11 49 04

**Comment by ywalia01** [comment]
Like this?

**Comment by rahul799** [comment]
No. I am asking about the output. The news page.

**Comment by ywalia01** [comment]
Screenshot 2020-06-05 at 12 12 33
Screenshot 2020-06-05 at 12 13 11

**Comment by ywalia01** [comment]
Note:
The text below newsletter has been edited by me in my latest branch, and is not present in this(current) pr. Rest of the page is same.

**Comment by rahul799** [comment]
@ywalia01 good job. Now instead of showing all in one column, can you make it like a grid of 3 columns? Will you like to work on it?

**Comment by ywalia01** [comment]
Ok, will do.

**Pull request closed without merging**
