### PR TITLE
Add News Page #2

### PR DESCRIPTION
**Pull request by Kushagraw12**
News Page added

### CODE REVIEW

**Comment by rahul799** [comment]
good job @Kushagraw12 . Can you please attach a screenshot of the output page.

**Comment by Kushagraw12** [comment]
Sure :)
output ss

**Comment by Kushagraw12** [comment]
There are modals as well, which open up when the news heading is clicked!
Screenshot (34)

**Comment by rahul799** [comment]
Good job @Kushagraw12.

**Comment by Kushagraw12** [comment]
Thanks @rahul799 !! 
Why did you revert it though?

**Comment by rahul799** [comment]
sorry for that @Kushagraw12. I have made this issue intentionally so that others( & I will not close it even if the problem is solved) can also learn & I was about to merge it in some different branch but by mistake, I merged it in the master. That's why.

**Comment by Kushagraw12** [comment]
Ohhkayy, i get it.

**Pull request merged**
