### PR TITLE
Added news.html

### PR DESCRIPTION
**Pull request by jradha11**
I have added the template for news.html in which there are sections for different categories of news(eg education, technology so forth). Each card of the news displays its headline, date of publication, and a short description. The whole news can be viewed by clicking the read more link.

### CODE REVIEW

**Comment by jradha11** [comment]
image

Here is a screenshot of the page

**Comment by jradha11** [comment]
@rahul799 review requested

**Comment by rahul799** [comment]
sorry @jradha11 for the delay.

**Comment by rahul799** [comment]
@jradha11 it looks good & can be merged but I want to give you one more task.
Please add some cool animations inside the boxes & add the commits here.

**Comment by jradha11** [comment]
Sure.

**Review by CapTen101 — APPROVED** [review]

**Pull request closed without merging**
